[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "aiosqlite>=0.19.0,<1.0.0",
    "alembic>=1.16.5",
    "asyncpg>=0.29.0,<1.0.0",
    "bcrypt==4.0.1",
    "beautifulsoup4>=4.13.5",
    "black>=23.0.0,<24.0.0",
    "dask[complete]>=2024.8.0",
    "email-validator>=2.3.0",
    "factory-boy>=3.3.0,<4.0.0",
    "faker>=19.0.0,<20.0.0",
    "fastapi>=0.104.0,<1.0.0",
    "flake8>=6.0.0,<7.0.0",
    "geopandas>=0.14.0,<0.15.0",
    "httpx>=0.25.0,<1.0.0",
    "ipython>=8.18.1",
    "isort>=5.12.0,<6.0.0",
    "jinja2>=3.1.0,<4.0.0",
    "jupyter>=1.1.1",
    "kaggle>=1.7.4.5",
    "matplotlib>=3.9.4",
    "mypy>=1.6.0,<2.0.0",
    "numba>=0.60.0",
    "numpy>=1.24.0,<2.0.0",
    "openml>=0.15.1",
    "pandas>=2.0.0",
    "pyproj>=3.6.0,<3.7.0",
    "passlib[bcrypt]>=1.7.4,<2.0.0",
    "plotly>=6.3.0",
    "psutil>=5.9.0,<6.0.0",
    "psycopg2-binary>=2.9.10",
    "libpysal>=4.10.0,<5.0.0",
    "esda>=2.5.0,<3.0.0",
    "pydantic>=2.4.0,<3.0.0",
    "pydantic-settings>=2.0.0,<3.0.0",
    "pytest>=7.4.0,<8.0.0",
    "pytest-asyncio>=0.21.0,<1.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
    "python-dotenv>=1.0.0",
    "python-jose[cryptography]>=3.3.0,<4.0.0",
    "python-multipart>=0.0.6,<1.0.0",
    "langid>=1.1.6",
    "vadersentiment>=3.3.2",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "shapely>=2.0.2,<2.1.0",
    "rtree>=1.3.0,<2.0.0",
    "sqlalchemy[asyncio]>=2.0.0,<3.0.0",
    "tqdm>=4.67.1",
    "uvicorn[standard]>=0.24.0,<1.0.0",
    "xgboost>=2.1.4",
]
